### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by pkliczewski**
Release of v1.0.8.

Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

### CODE REVIEW

**Comment by masayag** [comment]
@pkliczewski the PR looks good, but it fails for uncommitted changes

**Comment by pkliczewski** [comment]
> @pkliczewski the PR looks good, but it fails for uncommitted changes

Yeah, I see this everytime I release. I do:
find & replace version
mvn clean deploy -P release 
git add
git commit and tag
find & replace version
mvn clean install
git add
git commit and pus

@nirarg there seems to be an issue with notification sdk generation

**Comment by RichardW98** [comment]
> @pkliczewski the PR looks good, but it fails for uncommitted changes

yes Piotr please run 'mvn clean install' in your local and check in the changes in sdk

**Comment by pkliczewski** [comment]
> yes Piotr please run 'mvn clean install' in your local and check in the changes in sdk

Running it second time helped.

**Pull request merged**
