### PR TITLE
FLPATH-303: workflow rollback

### PR DESCRIPTION
**Pull request by RichardW98**
**What this PR does / why we need it**:
1) User may want to rollback executions if the workflow is failed

2) misleading swagger response with list:

Screenshot 2023-05-09 at 4 22 54 PM

**Which issue(s) this PR fixes**:
Fixes #[FLPATH-303](https://issues.redhat.com//browse/FLPATH-303) #[FLPATH-358](https://issues.redhat.com//browse/FLPATH-358)

**Change type**
- [x] New feature
- [ ] Bug fix
- [ ] Unit tests
- [ ] Integration tests
- [ ] CI
- [ ] Documentation
- [x] Auto-generated SDK code

**Impacted services**
- [x] Workflow Service
- [ ] Notification Service

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.

### CODE REVIEW

**Review by pkliczewski — COMMENTED** [review]
Please add rollback example and integration test.

How user can specify whether to run rollback or not?

**Comment by RichardW98** [comment]
> Please add rollback example and integration test.
> 
> How user can specify whether to run rollback or not?

I will add some instruction in readme

**Review by pkliczewski — COMMENTED** [review]
/lgtm

**Review by anludke — APPROVED** [review]
/lgtm

**Pull request merged**
