### PR TITLE
Introduce checkstyle to enforce conventions

### PR DESCRIPTION
**Pull request by masayag**
**What this PR does / why we need it**:
We'd like to make sure our code base is aligned with its conventions.

**Which issue(s) this PR fixes** :
Fixes #[FLPATH-347](https://issues.redhat.com//browse/FLPATH-347)

**Change type**
- [ ] New feature
- [ ] Bug fix
- [ ] Unit tests
- [ ] Integration tests
- [ ] CI
- [ ] Documentation
- [ ] Auto generated SDK code

**Impacted services**
- [ ] Workflow Service
- [ ] Notification Service

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.

### CODE REVIEW

**Comment by masayag** [comment]
This PR is going to heavily fail since our code base doesn't entirely match the convention of spring.
For that, we'll have to disable the rules and gradually add them when fixed.
I suggest enabling the checkstyle plugin per module to make the work sustainable and not too overwhelming. 
I'll introduce a set of rules to be excluded in next commits of this PR.

**Review by pkliczewski — COMMENTED** [review]
/lgtm

**Comment by gciavarrini** [comment]
@masayag may I suggest updating the `Makefile` target `format-files`?

**Comment by masayag** [comment]
> @masayag may I suggest updating the `Makefile` target `format-files`?

@gciavarrini as the name and the action suggests - `format-files` changes the files.
with checkstyle, all can be done is `check` action, not modify the files. Hence it doesn't fit.

**Pull request merged**
