### PR TITLE
Exclude notification-service-sdk from coverage

### PR DESCRIPTION
**Pull request by gciavarrini**
**What this PR does / why we need it**:
Since ` notification-service-sdk` module contains auto-generated code, it shouldn't be part of the coverage (like`workflow-service-sdk`)

**Change type**
- [ ] New feature
- [x] Bug fix
- [ ] Unit tests
- [ ] Integration tests
- [ ] CI
- [ ] Documentation
- [ ] Auto generated SDK code

**Impacted services**
- [ ] Workflow Service
- [x] Notifivcation Service

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.

### CODE REVIEW

**Comment by eloycoto** [comment]
Could you update the coverage trigger to 68?

**Review by pkliczewski — COMMENTED** [review]
lgtm

**Comment by masayag** [comment]
> Could you update the coverage trigger to 68?

Is there an option to include the code coverage result on the main project page badget + build status?
Also, wasn't able to find (again...) the code coverage statistics. Where can it be viewed?

**Comment by eloycoto** [comment]
>Is there an option to include the code coverage result on the main project page badget + build status?

I'm not aware of that, there is a plugin for this and it's hard to get the value from it :-( 


> Also, wasn't able to find (again...) the code coverage statistics. Where can it be viewed?

It's an step in the Actions:
https://github.com/parodos-dev/parodos/actions/runs/4913907151/jobs/8774725848?pr=318

And per each PullRequest, you can see the output in the summary:
https://github.com/parodos-dev/parodos/actions/runs/4913907151?pr=318#summary-13309018595

**Review by RichardW98 — APPROVED** [review]

**Pull request merged**
