### PR TITLE
feat: move backstage to sqlite

### PR DESCRIPTION
**Pull request by eloycoto**
Other day Paul mentioned that you can use sqlite, to avoid the issues with  postgres we can use the following configuration to avoid demo errors

### CODE REVIEW

**Comment by eloycoto** [comment]
@gciavarrini  wdyt?

**Comment by pkliczewski** [comment]
Would it be possible to keep both? I think we can learn about how to use postgresql well [here](https://backstage.io/docs/deployment/k8s#creating-the-postgresql-database)

**Comment by gciavarrini** [comment]
> Would it be possible to keep both? I think we can learn about how to use postgresql well [here](https://backstage.io/docs/deployment/k8s#creating-the-postgresql-database)

@pkliczewski postgress seems to workfine after this changes https://github.com/gciavarrini/parodos/tree/fix-openshift-postegres 
Not sure if this can be helpful for this PR

**Comment by pkliczewski** [comment]
> @pkliczewski postgress seems to workfine after this changes https://github.com/gciavarrini/parodos/tree/fix-openshift-postegres Not sure if this can be helpful for this PR

I would love to keep both

**Comment by eloycoto** [comment]
The thing is that with the changes that @gciavarrini introduces may not work on kind, I would like to be as simple as possible.  Having postgres in there only adds some burden and maybe a user will use like that

**Comment by eloycoto** [comment]
> @eloycoto what is our recommended way to deploy backstage? do we want customers to use sqlite?

Do we want our customers to use a single pod with a postgres without backup/failover/replication etc..? The Postgres that we have it's just for running backstage, we no longer need that.. so I would drop it. 

Having two backstage means that we need to keep two files up to date, moving things around, plus all the problems that @gciavarrini discovered on running an example Postgres in openshift.

**Comment by pkliczewski** [comment]
@eloycoto do we still need this change?

**Comment by eloycoto** [comment]
I would love to have that :D let's keep this on-hold.

**Pull request closed without merging**
